"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, BadgeCheck, Calculator, CheckCircle2, ClipboardCheck, FileCheck2, Landmark, Plus, Upload, Wallet, X } from "lucide-react";
import { useManagement } from "@/contexts/ManagementContext";
import { useAuth } from "@/contexts/AuthContext";
import { currency, dateToday, RecordData, str } from "@/domain/management/model";
import { commitRecords, saveManagement } from "@/services/managementService";
import { nameFileForDrive, uploadFileToDrive } from "@/services/driveService";
import "@/components/management/management.css";

const n=(value:FormDataEntryValue|null)=>Math.max(0,Math.round(Number(value||0)*100));
const brl=(value:number)=>currency(Math.round(value));
const parseBankAmounts=(row:RecordData):Record<string,{credit:number;debit:number;pix:number}>=>{try{return JSON.parse(str(row,"bankAmountsJson")||"{}")}catch{return {}}};

export function CashWorkspace({ mode }: { mode: "closing" | "conference" }) {
  const { data } = useManagement(); const { userProfile }=useAuth();
  const [closingOpen,setClosingOpen]=useState(false); const [reviewing,setReviewing]=useState<RecordData|null>(null); const [message,setMessage]=useState("");
  useEffect(()=>{if(mode!=="closing")return;const open=()=>setClosingOpen(true);window.addEventListener("open-cashClosings-form",open);return()=>window.removeEventListener("open-cashClosings-form",open);},[mode]);
  const today=dateToday(); const closings=data.cashClosings.filter(row=>!row.archived).sort((a,b)=>str(b,"date").localeCompare(str(a,"date")));
  const visible=mode==="closing"?(userProfile?.role==="operator"?closings.filter(r=>r.unitId===userProfile.unitId):closings):closings.filter(r=>r.status!=="Rascunho");
  const todayRows=visible.filter(r=>str(r,"date")===today); const difference=todayRows.reduce((sum,row)=>sum+Number(row.difference||0),0); const pending=closings.filter(row=>row.status==="Aguardando conferência"||row.status==="Com divergência");
  return <div className="workspace-shell cash-workspace">
    <header className="workspace-header"><div><span className="workspace-eyebrow">FECHAMENTO DE CAIXA HOUSE 190</span><h1>{mode==="closing"?"Fechamento de caixa":"Conferência e auditoria de caixa"}</h1><p>{mode==="closing"?"Sistema, dinheiro, cartões, PIX, máquinas, sangrias e divergências em um fechamento completo.":"Revise os valores enviados e confirme antes de atualizar cada saldo bancário."}</p></div>{mode==="closing"&&<button className="workspace-primary" onClick={()=>setClosingOpen(true)}><Plus size={16}/> Novo fechamento</button>}</header>
    <section className="workspace-metrics"><Metric icon={Wallet} tone="purple" label="Registros de hoje" value={String(todayRows.length)}/><Metric icon={Calculator} tone="blue" label="Diferença do dia" value={brl(difference)}/><Metric icon={AlertTriangle} tone="red" label="Aguardando financeiro" value={String(pending.length)}/><Metric icon={CheckCircle2} tone="green" label="Conferidos" value={String(closings.filter(r=>r.status==="Conferido").length)}/></section>
    {message&&<p className="workspace-message">{message}</p>}
    <section className="cash-list"><header><div><span>{mode==="closing"?"HISTÓRICO":"FILA FINANCEIRA"}</span><h2>{mode==="closing"?"Fechamentos registrados":"Caixas para conferência"}</h2></div><b>{visible.length}</b></header>
      {visible.length?visible.map(row=>{const unit=data.units.find(u=>u.id===row.unitId);return <article key={row.id}><div className="cash-status-icon"><ClipboardCheck size={18}/></div><div><strong>{unit?.name||"Unidade"}</strong><span>{str(row,"date").split("-").reverse().join("/")} · {str(row,"shift")} · {str(row,"operatorName")}</span></div><div><small>Total informado</small><b>{currency(Number(row.countedTotal||0))}</b></div><div><small>Diferença</small><b className={Number(row.difference||0)===0?"ok":"bad"}>{currency(Number(row.difference||0))}</b></div><span className={`cash-badge ${str(row,"status").toLowerCase().replaceAll(" ","-")}`}>{str(row,"status")}</span>{mode==="conference"&&row.status!=="Conferido"&&<button className="workspace-primary" onClick={()=>setReviewing(row)}><BadgeCheck size={15}/> Conferir</button>}</article>}):<div className="people-empty"><FileCheck2 size={30}/><strong>Nenhum fechamento encontrado</strong><span>{mode==="closing"?"Use “Novo fechamento” para iniciar.":"Nenhum caixa aguardando conferência."}</span></div>}
    </section>
    {closingOpen&&<ClosingModal onClose={()=>setClosingOpen(false)} onSaved={()=>{setClosingOpen(false);setMessage("Fechamento enviado ao financeiro para conferência.");}}/>}
    {reviewing&&<ConferenceModal closing={reviewing} onClose={()=>setReviewing(null)} onSaved={()=>{setReviewing(null);setMessage("Conferência aprovada e saldos bancários atualizados.");}}/>}
  </div>;
}

function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="mg-modal-shade"><div className={`mg-modal ${wide?"cash-modal-wide":""}`} role="dialog" aria-modal="true"><header><h2>{title}</h2><button onClick={onClose}><X size={20}/></button></header>{children}</div></div>}

function ClosingModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){
  const {data,tenantId,allowedUnit}=useManagement();const {user,userProfile}=useAuth();const [unit,setUnit]=useState(allowedUnit==="all"?"":allowedUnit);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [calc,setCalc]=useState({system:0,counted:0,difference:0,motoboyDifference:0,invoiceDifference:0});
  const banks=data.bankAccounts.filter(row=>!row.archived&&row.unitId===unit);
  const recalc=(form:HTMLFormElement)=>{const f=new FormData(form);const systemCash=n(f.get("systemCash")),systemCard=n(f.get("systemCredit"))+n(f.get("systemDebit")),systemPix=n(f.get("systemPix")),systemIfood=n(f.get("systemIfood"));let cards=0,pix=0;banks.forEach(bank=>{cards+=n(f.get(`credit_${bank.id}`))+n(f.get(`debit_${bank.id}`));pix+=n(f.get(`pix_${bank.id}`));});const expectedCash=n(f.get("openingAmount"))+systemCash+n(f.get("cashIn"))-n(f.get("withdrawals"))-n(f.get("closingFloat"));const countedCash=n(f.get("countedCash"));const difference=countedCash-expectedCash+cards-systemCard+pix-systemPix;setCalc({system:systemCash+systemCard+systemPix+systemIfood,counted:countedCash+cards+pix,difference,motoboyDifference:n(f.get("motoboyPaid"))-n(f.get("motoboySystem")),invoiceDifference:n(f.get("ifoodAudit"))+n(f.get("fiscalMachines"))-n(f.get("invoiceIssued"))});};
  return <Modal title="Novo fechamento de caixa" onClose={onClose} wide><form className="cash-form" onChange={e=>recalc(e.currentTarget)} onSubmit={async event=>{event.preventDefault();if(!user)return;setBusy(true);setError("");try{const f=new FormData(event.currentTarget);const bankAmounts:Record<string,{credit:number;debit:number;pix:number}>={};banks.forEach(bank=>bankAmounts[bank.id]={credit:n(f.get(`credit_${bank.id}`)),debit:n(f.get(`debit_${bank.id}`)),pix:n(f.get(`pix_${bank.id}`))});const files=f.getAll("attachments").filter(x=>x instanceof File&&x.size) as File[];if(files.length>5)throw new Error("Envie no máximo 5 comprovantes.");const attachments=[];for(const file of files){const saved=await uploadFileToDrive(nameFileForDrive(file,`Fechamento ${String(f.get("date"))} - ${unit}`),"payment_proofs");attachments.push({fileId:saved.fileId,fileName:saved.fileName,mimeType:saved.mimeType,size:saved.size});}const now=new Date().toISOString();const row:RecordData={id:`closing-${String(f.get("date"))}-${unit}-${String(f.get("shift")).toLowerCase().replaceAll(" ","-")}`,kind:"cashClosings",tenantId,unitId:unit,version:0,createdAt:now,updatedAt:now,createdBy:user.uid,updatedBy:user.uid,date:String(f.get("date")),shift:String(f.get("shift")),operatorName:String(f.get("operatorName")),systemCash:n(f.get("systemCash")),systemCredit:n(f.get("systemCredit")),systemDebit:n(f.get("systemDebit")),systemPix:n(f.get("systemPix")),systemIfood:n(f.get("systemIfood")),openingAmount:n(f.get("openingAmount")),cashIn:n(f.get("cashIn")),withdrawals:n(f.get("withdrawals")),closingFloat:n(f.get("closingFloat")),countedCash:n(f.get("countedCash")),bankAmountsJson:JSON.stringify(bankAmounts),systemTotal:calc.system,countedTotal:calc.counted,difference:calc.difference,motoboySystem:n(f.get("motoboySystem")),motoboyPaid:n(f.get("motoboyPaid")),motoboyDifference:calc.motoboyDifference,ifoodAudit:n(f.get("ifoodAudit")),fiscalMachines:n(f.get("fiscalMachines")),invoiceIssued:n(f.get("invoiceIssued")),invoiceDifference:calc.invoiceDifference,attachmentsJson:JSON.stringify(attachments),status:"Aguardando conferência",notes:String(f.get("notes")||"")};await saveManagement(row,data);onSaved();}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o fechamento.");}finally{setBusy(false);}}}>
    <section><h3>1. Identificação</h3><div className="cash-fields"><label>Unidade<select required value={unit} disabled={allowedUnit!=="all"} onChange={e=>setUnit(e.target.value)}><option value="">Selecione</option>{data.units.filter(u=>!u.archived&&(allowedUnit==="all"||u.id===allowedUnit)).map(u=><option key={u.id} value={u.id}>{str(u,"name")}</option>)}</select></label><label>Data<input name="date" type="date" defaultValue={dateToday()} required/></label><label>Turno<select name="shift" required><option>Almoço</option><option>Jantar</option><option>Dia inteiro</option></select></label><label>Operador<input name="operatorName" defaultValue={userProfile?.displayName||""} required/></label></div></section>
    <section><h3>2. Valores do sistema</h3><div className="cash-fields five"><Money name="systemCash" label="Dinheiro"/><Money name="systemCredit" label="Crédito"/><Money name="systemDebit" label="Débito"/><Money name="systemPix" label="PIX"/><Money name="systemIfood" label="iFood"/></div></section>
    <section><h3>3. Dinheiro físico</h3><div className="cash-fields five"><Money name="openingAmount" label="Fundo inicial"/><Money name="cashIn" label="Suprimentos"/><Money name="withdrawals" label="Sangrias/saídas"/><Money name="closingFloat" label="Troco mantido"/><Money name="countedCash" label="Dinheiro contado"/></div></section>
    <section><h3>4. Cartões e PIX por banco/máquina</h3>{banks.length?<div className="machine-grid">{banks.map(bank=><article key={bank.id}><strong><Landmark size={15}/>{str(bank,"name")}</strong><Money name={`credit_${bank.id}`} label="Crédito"/><Money name={`debit_${bank.id}`} label="Débito"/><Money name={`pix_${bank.id}`} label="PIX"/></article>)}</div>:<p className="cash-hint">Selecione a unidade para carregar seus bancos.</p>}</section>
    <section><h3>5. Auditorias obrigatórias</h3><div className="audit-grid"><article><strong>Motoboys</strong><Money name="motoboySystem" label="Valor no sistema"/><Money name="motoboyPaid" label="Valor pago"/><b>Diferença: {brl(calc.motoboyDifference)}</b></article><article><strong>Notas fiscais</strong><Money name="ifoodAudit" label="Valor iFood"/><Money name="fiscalMachines" label="Máquinas fiscais"/><Money name="invoiceIssued" label="NF emitida"/><b>Diferença: {brl(calc.invoiceDifference)}</b></article></div></section>
    <section><h3>6. Resultado e documentos</h3><div className="closing-result"><div><span>Sistema</span><strong>{brl(calc.system)}</strong></div><div><span>Contado</span><strong>{brl(calc.counted)}</strong></div><div className={calc.difference===0?"ok":"bad"}><span>Diferença</span><strong>{brl(calc.difference)}</strong></div></div><label className="employee-file-upload"><Upload size={15}/> Anexar comprovantes no Google Drive<input name="attachments" type="file" multiple className="sr-only" accept=".pdf,image/*"/></label><label>Ocorrências<textarea name="notes" rows={3}/></label></section>
    {error&&<p className="mg-error">{error}</p>}<footer><button type="button" className="mg-button secondary" onClick={onClose}>Cancelar</button><button className="mg-button" disabled={busy||!unit}>{busy?"Enviando…":"Enviar ao financeiro"}</button></footer>
  </form></Modal>
}

function ConferenceModal({closing,onClose,onSaved}:{closing:RecordData;onClose:()=>void;onSaved:()=>void}){
  const {data,tenantId}=useManagement();const {user,userProfile}=useAuth();const [review,setReview]=useState(false);const saved=parseBankAmounts(closing);const [values,setValues]=useState<Record<string,number>>(()=>Object.fromEntries(data.bankAccounts.filter(b=>!b.archived&&b.unitId===closing.unitId).map(b=>[b.id,Object.values(saved[b.id]||{}).reduce((s,v)=>s+Number(v||0),0)])));const [busy,setBusy]=useState(false);const [error,setError]=useState("");const banks=data.bankAccounts.filter(b=>!b.archived&&b.unitId===closing.unitId);
  const save=async()=>{if(!user)return;setBusy(true);setError("");try{const now=new Date().toISOString();const before=Object.fromEntries(banks.map(b=>[b.id,typeof b.balance==="number"?b.balance:null]));const updates=banks.map(bank=>({...bank,balance:Math.round(values[bank.id]||0),balanceDate:str(closing,"date"),reconciled:true,updatedAt:now,updatedBy:user.uid}));const conference:RecordData={id:`conference-${closing.id}`,kind:"cashConferences",tenantId,unitId:closing.unitId,version:0,createdAt:now,updatedAt:now,createdBy:user.uid,updatedBy:user.uid,date:str(closing,"date"),closingId:closing.id,operatorName:str(closing,"operatorName"),beforeBalancesJson:JSON.stringify(before),afterBalancesJson:JSON.stringify(values),difference:Number(closing.difference||0),status:"Conferido",reviewedBy:userProfile?.displayName||user.email||user.uid,notes:"Saldos bancários confirmados após conferência financeira."};const updatedClosing={...closing,status:"Conferido",updatedAt:now,updatedBy:user.uid};await commitRecords([...updates,conference,updatedClosing],data,conference);onSaved();}catch(e){setError(e instanceof Error?e.message:"Não foi possível concluir a conferência.");}finally{setBusy(false);}};
  return <Modal title="Conferir e atualizar saldos" onClose={onClose} wide><div className="conference-flow"><div className="conference-summary"><span>FECHAMENTO</span><strong>{str(closing,"date").split("-").reverse().join("/")} · {str(closing,"shift")}</strong><small>Operador: {str(closing,"operatorName")} · Diferença: {currency(Number(closing.difference||0))}</small></div><p className="cash-warning"><AlertTriangle size={17}/> Os valores abaixo substituirão a posição atual de cada banco somente após a confirmação final.</p><div className="conference-banks">{banks.map(bank=><label key={bank.id}><span><Landmark size={15}/>{str(bank,"name")}</span><small>Saldo atual: {typeof bank.balance==="number"?currency(Number(bank.balance)):"Não informado"}</small><input type="number" step="0.01" min="0" value={(values[bank.id]||0)/100} disabled={review} onChange={e=>setValues(v=>({...v,[bank.id]:Math.round(Number(e.target.value)*100)}))}/>{review&&<b>Novo saldo: {currency(values[bank.id]||0)}</b>}</label>)}</div>{review&&<div className="confirmation-box"><CheckCircle2 size={22}/><div><strong>Confirme a atualização dos bancos</strong><p>Esta ação registrará a auditoria, o responsável e os valores anteriores e novos.</p></div></div>}{error&&<p className="mg-error">{error}</p>}<footer><button className="mg-button secondary" onClick={review?()=>setReview(false):onClose}>{review?"Voltar e corrigir":"Cancelar"}</button><button className="mg-button" disabled={busy||!banks.length} onClick={review?save:()=>setReview(true)}>{busy?"Atualizando…":review?"Confirmar e atualizar bancos":"Revisar atualização"}</button></footer></div></Modal>
}

function Money({name,label}:{name:string;label:string}){return <label>{label}<input name={name} type="number" step="0.01" min="0" defaultValue="0"/></label>}
function Metric({icon:Icon,tone,label,value}:{icon:typeof ClipboardCheck;tone:string;label:string;value:string}){return <div className={`workspace-metric ${tone}`}><span><Icon size={18}/></span><div><small>{label}</small><strong className={value.length>8?"compact":""}>{value}</strong></div></div>}
