import {
  Activity,
  ArrowDownToLine,
  Bell,
  Building2,
  Calculator,
  CalendarDays,
  ChartNoAxesCombined,
  CheckSquare,
  Database,
  FileBarChart,
  FolderLock,
  Gauge,
  Landmark,
  LayoutDashboard,
  Package,
  Receipt,
  ShieldCheck,
  Target,
  TrendingUp,
  Users,
  Wallet,
} from "lucide-react";
export const MANAGEMENT_NAV = [
  { title: "Saúde do Negócio", href: "/", icon: LayoutDashboard },
  { title: "Painel do Dono", href: "/painel-do-dono", icon: Activity },
  { title: "Faturamento", href: "/faturamento", icon: TrendingUp },
  { title: "Metas", href: "/metas", icon: Target },
  { title: "Financeiro", href: "/financeiro", icon: Wallet },
  { title: "Contas a pagar", href: "/contas-a-pagar", icon: CalendarDays },
  {
    title: "Contas a receber",
    href: "/contas-a-receber",
    icon: ArrowDownToLine,
  },
  {
    title: "Fluxo de caixa",
    href: "/fluxo-de-caixa",
    icon: ChartNoAxesCombined,
  },
  { title: "DRE gerencial", href: "/dre", icon: FileBarChart },
  { title: "Compras e estoque", href: "/compras-estoque", icon: Package },
  { title: "RH e folha", href: "/folha", icon: Users },
  { title: "Impostos", href: "/fiscal", icon: Receipt },
  { title: "Empréstimos", href: "/dividas", icon: Landmark },
  { title: "Indicadores", href: "/indicadores", icon: Gauge },
  { title: "Alertas", href: "/alertas", icon: Bell },
  { title: "Comparativo", href: "/comparativo", icon: Building2 },
  { title: "Orçamento", href: "/orcamento", icon: Calculator },
  { title: "Fechamento", href: "/fechamento", icon: ShieldCheck },
  { title: "Reunião semanal", href: "/reuniao", icon: CheckSquare },
  { title: "Bases de gestão", href: "/bases", icon: Database },
  { title: "Documentos", href: "/documentos", icon: FolderLock },
  { title: "RH anterior", href: "/rh", icon: Users },
  { title: "Financeiro anterior", href: "/legado/financeiro", icon: Wallet },
  {
    title: "Faturamento anterior",
    href: "/legado/faturamento",
    icon: TrendingUp,
  },
];
